config/routes.rb
LivestreamPreview::Application.routes.draw do
  root :to => 'channels#index'

  resources :channels, :only => :index
  match 'channels/pages/:page', :to => 'channels#index', :as => 'paged_channels'
end

app/models/channel.rb
class Channel
  include HTTParty

  base_uri 'channelguide.api.livestream.com'
  default_params :affiliateId => 2065, :applicationKey => '40dea23023e15c6730a6db8a069c60b0b4dbb646'
  
  def self.most_popular_channels(page_number = 1, results_per_page = 8)
    response = get('/programguide',
                   :query => {:method => 'getMostViewedChannels',
                     :pageNumber => page_number,
                     :resultsPerPage => results_per_page,
                     :mostViewedChannelType => 'NOW'})

    if response.success?
      channels = response.parsed_response['response']['channels']['channel']
    else
      channels = []
    end

    channels.map do |channel|
      new(:id => channel['id'],
          :short_name => channel['shortName'],
          :full_name => channel['fullName'],
          :logo_url => channel['logoURL'],
          :live => channel['live'])
    end
  end

  attr_accessor :id, :short_name, :full_name, :logo_url

  def initialize(params = {})
    @id = params[:id].to_i
    @short_name = params[:short_name].to_s
    @full_name = params[:full_name].to_s
    @logo_url = params[:logo_url].to_s
    @live = params[:live] == 'true'
  end

  def live?
    @live
  end

  def url
    "http://livestream.com/#{short_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @page = (params[:page] || 1).to_i
    @channels = Channel.most_popular_channels(@page)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channels/index.html.erb
<h1>Popular Livestream Channels</h1>
<% @channels.each_with_index do |channel, index| %>
<% if index % 4 == 0 %><div class="row"><% end %>
  <div class="channel">
    <% if channel.live? %>
      <img id="thumbnail_<%= channel.id %>" class="thumbnail" src="http://thumbnail.api.livestream.com/thumbnail?name=<%= channel.short_name %>" alt="" />
      <script type="text/javascript">
        setInterval(function () { updateThumb('<%= channel.id %>', '<%= channel.short_name %>') }, 3000);
      </script>
    <% elsif !channel.logo_url.blank? %>
      <img style="width: 100px; height: 100px" src="<%= channel.logo_url %>" alt="" />
    <% end %>
    <p><a href="<%= channel.url %>"><%= channel.full_name %></a></p>
  </div>
  <% if index % 4 == 3 || index == @channels.size %></div><% end %>
<% end %>
<hr/>
<p><%= link_to 'Previous', paged_channels_path(:page => @page.pred) if @page > 1 %>
<%= link_to 'Next', paged_channels_path(:page => @page.next), :class => 'right' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LivestreamPreview</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="container">
<%= yield %>
</div>

</body>
</html>